version: '3'
services:
  devops:
    image: vamshi9133/carrepotransport:latest
    ports:
      - "90:80"
    deploy:
      replicas: 3

  aws:
    image: vamshi9133/bikerepotransport:latest
    ports:
      - "91:80"
    deploy:
      replicas: 3

  datascience:
    image: vamshi9133/jeeprepotransport:latest
    ports:
      - "92:80"
    deploy:
      replicas: 3

  azure:
    image: vamshi9133/busrepotransport:latest
    ports:
      - "93:80"
    deploy:
      replicas: 3
